### ISSUE TITLE
Haskell Script

### ISSUE THREAD

**Issue by droidforever** [bneijt/mullvad-edgerouter-x#2]
Could you tell me how to run your script on an er-x router?  How do I install Haskell?  After installing what is the command line to run the script.

**Comment by bneijt** [comment]
No, the program is meant to be run locally on a machine to generate a configuration script which you can copy paste into the SSH terminal of the edgerouter.

I wrote this in Haskell because I was learning that language, but I realize that this is way to complicated for most people and will rewrite this simple formatting script into either python or a javascript website (but people are probably hesitant to copy their key into a web interface, so Python should be the best option...)

**Comment by bneijt** [comment]
I've updated the README and converted everything to Python which should make it really easy to run.

I'll be adding more information in the README at a later stage, but it should be much clearer to use now. Thank you for your feedback and creating this issue.
